// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `sendRecvDemo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var communication = __M.module("communication");

    communication.Receiver = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::communication::Receiver"
        ],
        -1, undefined, undefined, false);

    communication.ReceiverPrx = Slice.defineProxy(Ice.ObjectPrx, communication.Receiver.ice_staticId, undefined);

    Slice.defineOperations(communication.Receiver, communication.ReceiverPrx,
    {
        "callback": [, , , , , , [[3]], , , , ]
    });

    communication.Sender = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::communication::Sender"
        ],
        -1, undefined, undefined, false);

    communication.SenderPrx = Slice.defineProxy(Ice.ObjectPrx, communication.Sender.ice_staticId, undefined);

    Slice.defineOperations(communication.Sender, communication.SenderPrx,
    {
        "addClient": [, , , , , , [[Ice.Identity]], , , , ]
    });
    exports.communication = communication;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : this.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : this));
