// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `system.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var system = __M.module("system");

    /**
     * 地区信息模型
     **/
    system.Area = Slice.defineStruct(
        function(areac, arean, cyprnh, qtc, cstatus)
        {
            this.areac = areac !== undefined ? areac : 0;
            this.arean = arean !== undefined ? arean : "";
            this.cyprnh = cyprnh !== undefined ? cyprnh : 0;
            this.qtc = qtc !== undefined ? qtc : "";
            this.cstatus = cstatus !== undefined ? cstatus : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.areac);
            __os.writeString(this.arean);
            __os.writeLong(this.cyprnh);
            __os.writeString(this.qtc);
            __os.writeInt(this.cstatus);
        },
        function(__is)
        {
            this.areac = __is.readInt();
            this.arean = __is.readString();
            this.cyprnh = __is.readLong();
            this.qtc = __is.readString();
            this.cstatus = __is.readInt();
        },
        18, 
        false);
    Slice.defineSequence(system, "AreaSeqHelper", "system.Area", false);

    /**
     * 系统服务接口
     **/
    system.SystemService = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::system::SystemService"
        ],
        -1, undefined, undefined, false);

    system.SystemServicePrx = Slice.defineProxy(Ice.ObjectPrx, system.SystemService.ice_staticId, undefined);

    Slice.defineOperations(system.SystemService, system.SystemServicePrx,
    {
        "getViaCity": [, , , , , [7], [[3], [3]], , , , ],
        "getAllDict": [, , , , , [7], , , , , ],
        "getChineseAllAreas": [, , , , , [7], , , , , ],
        "getChineseAllAreasByPc": [, , , , , [7], , , , , ],
        "getTransferPoint": [, , , , , [7], [[3]], , , , ],
        "getCityAreaAll": [, , , , , [7], , , , , ],
        "getCityAreaAll4H5": [, , , , , [7], , , , , ],
        "getProperties": [, , , , , [7], , , , , ],
        "getCityByName": [, , , , , [7], [[7]], , , , ]
    });
    exports.system = system;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : this.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : this));
